In [2]:
import torch
from timm import create_model

feature_extractor = create_model(
    'resnet18',
    pretrained=True,
    features_only=True
)
feature_extractor.eval()
batch_size = 5
img = torch.randn(batch_size, 3, 256, 256)
for i, v in enumerate(feature_extractor(img)):
    print(f'{i} : {v.shape}')

0 : torch.Size([5, 64, 128, 128])
1 : torch.Size([5, 64, 64, 64])
2 : torch.Size([5, 128, 32, 32])
3 : torch.Size([5, 256, 16, 16])
4 : torch.Size([5, 512, 8, 8])


In [15]:
import torch.nn.functional as F

x = torch.randint(0, 5, (5, 3), dtype=torch.float)
y = torch.randn(3, 6, 7)
print(x)
print(F.normalize(x, p=1, dim=1))
print(F.normalize(x, p=2, dim=1))

tensor([[1., 3., 4.],
        [0., 4., 3.],
        [3., 4., 1.],
        [4., 1., 0.],
        [0., 3., 0.]])
tensor([[0.1250, 0.3750, 0.5000],
        [0.0000, 0.5714, 0.4286],
        [0.3750, 0.5000, 0.1250],
        [0.8000, 0.2000, 0.0000],
        [0.0000, 1.0000, 0.0000]])
tensor([[0.1961, 0.5883, 0.7845],
        [0.0000, 0.8000, 0.6000],
        [0.5883, 0.7845, 0.1961],
        [0.9701, 0.2425, 0.0000],
        [0.0000, 1.0000, 0.0000]])
